/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.inc;

import java.awt.BorderLayout;

import javax.swing.JPanel;

import view.FrMain;
import view.PnChucVu;
import view.PnFood;
import view.PnHoaDon;
import view.PnKho;
import view.PnNhanVien;
import view.PnNhapHang;
import view.PnThongKeTheoNgay;
import view.PnViTri;
import bean.User;

/**
 *
 * @author HungPham
 */
public class PnLeft extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private PnCenter pnCenter;

    /**
     * Creates new form PnLeft
     */
    FrMain fr;
    User login;
    public PnLeft(PnCenter pn , User login, FrMain fr) {
        initComponents();
        this.fr = fr;
        this.pnCenter = pn;
        this.login = login;
        lbUsername.setText("Xin chào! "+login.getFullname());
        lbChucVu.setText("Chức vụ: "+login.getChucvu());
        addPanel(new PnViTri("Quản lý vị trí", this, fr));
        if (login.getId_chucvu() == 1){
            
//        }else if (login.getId_chucvu() == 1)){
//            
//            this.remove(btChucVu);
//            btChucVu.setVisible(false);
        }else {
            btChucVu.setVisible(false);
            btNhanVien.setVisible(false);
            btFood.setVisible(false);
            btNhapHang.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbUsername = new javax.swing.JLabel();
        lbChucVu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btHoaDon = new javax.swing.JButton();
        btViTri = new javax.swing.JButton();
        btThongKe=new javax.swing.JButton();
        btFood = new javax.swing.JButton();
        btNhanVien = new javax.swing.JButton();
        btChucVu = new javax.swing.JButton();
        btKho = new javax.swing.JButton();
        btNhapHang=new javax.swing.JButton();
        jButton4.setText("jButton4");

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)), javax.swing.BorderFactory.createEtchedBorder()));

        lbUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbUsername.setText("Xin chào:");

        lbChucVu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbChucVu.setForeground(new java.awt.Color(255, 0, 0));
        lbChucVu.setText("Chức vụ:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(lbChucVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(0, 0, 0), java.awt.Color.white, java.awt.Color.white), "Quản lý", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED))));
        jPanel3.setMinimumSize(new java.awt.Dimension(104, 104));
        jPanel3.setPreferredSize(new java.awt.Dimension(104, 104));

        btHoaDon.setBackground(new java.awt.Color(204, 204, 204));
        btHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/app_48.png"))); // NOI18N
        btHoaDon.setText("HÓA ĐƠN");
        btHoaDon.setMaximumSize(new java.awt.Dimension(139, 57));
        btHoaDon.setMinimumSize(new java.awt.Dimension(139, 57));
        btHoaDon.setOpaque(false);
        btHoaDon.setPreferredSize(new java.awt.Dimension(139, 57));
        btHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoaDonActionPerformed(evt);
            }
        });
        jPanel3.add(btHoaDon);

        btViTri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/navigate_48.png"))); // NOI18N
        btViTri.setText("GỌI MÓN");
        btViTri.setMaximumSize(new java.awt.Dimension(139, 57));
        btViTri.setMinimumSize(new java.awt.Dimension(139, 57));
        btViTri.setPreferredSize(new java.awt.Dimension(139, 57));
        btViTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViTriActionPerformed(evt);
            }
        });
        jPanel3.add(btViTri);

        btFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coffee_48.png"))); // NOI18N
        btFood.setText("ĐỒ UỐNG");
        btFood.setMaximumSize(new java.awt.Dimension(139, 57));
        btFood.setMinimumSize(new java.awt.Dimension(139, 57));
        btFood.setPreferredSize(new java.awt.Dimension(139, 57));
        btFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFoodActionPerformed(evt);
            }
        });
        jPanel3.add(btFood);

        btNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_48.png"))); // NOI18N
        btNhanVien.setText("NHÂN VIÊN");
        btNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhanVienActionPerformed(evt);
            }
        });
        jPanel3.add(btNhanVien);

        btChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tabs_48.png"))); // NOI18N
        btChucVu.setText("CHỨC VỤ");
        btChucVu.setMaximumSize(new java.awt.Dimension(139, 57));
        btChucVu.setMinimumSize(new java.awt.Dimension(139, 57));
        btChucVu.setPreferredSize(new java.awt.Dimension(139, 57));
        btChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChucVuActionPerformed(evt);
            }
        });
        jPanel3.add(btChucVu);

        btKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/database_48.png"))); // NOI18N
        btKho.setText("KHO   ");
        btKho.setMaximumSize(new java.awt.Dimension(139, 57));
        btKho.setMinimumSize(new java.awt.Dimension(139, 57));
        btKho.setPreferredSize(new java.awt.Dimension(139, 57));
        btKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKhoActionPerformed(evt);
            }
        });
        jPanel3.add(btKho);
        
        btNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/box_download_48.png"))); // NOI18N
        btNhapHang.setText("NHẬP HÀNG");
        btNhapHang.setMaximumSize(new java.awt.Dimension(139, 57));
        btNhapHang.setMinimumSize(new java.awt.Dimension(139, 57));
        btNhapHang.setPreferredSize(new java.awt.Dimension(139, 57));
        btNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhapHangActionPerformed(evt);
            }
        });
        jPanel3.add(btNhapHang);
        
        btThongKe.setBackground(new java.awt.Color(204, 204, 204));
        btThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pie_chart.png"))); // NOI18N
        btThongKe.setText("THỐNG KÊ");
        btThongKe.setMaximumSize(new java.awt.Dimension(139, 57));
        btThongKe.setMinimumSize(new java.awt.Dimension(139, 57));
        btThongKe.setOpaque(false);
        btThongKe.setPreferredSize(new java.awt.Dimension(139, 57));
        btThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongKeActionPerformed(evt);
            }
        });
        jPanel3.add(btThongKe);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>                        

    private void btHoaDonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        addPanel(new PnHoaDon("Quản lý hóa đơn", fr));

    }                                        

    private void btViTriActionPerformed(java.awt.event.ActionEvent evt) {                                        
        addPanel(new PnViTri("Quản lý vị trí", this, fr));
    }                                       

    private void btFoodActionPerformed(java.awt.event.ActionEvent evt) {                                       
        addPanel(new PnFood("Quản lý thức uống"));
    }                                      
   
    private void btNhanVienActionPerformed(java.awt.event.ActionEvent evt) {                                           
        addPanel(new PnNhanVien("Quản lý nhân viên",login));
    }                                          

    private void btChucVuActionPerformed(java.awt.event.ActionEvent evt) {                                         
        addPanel(new PnChucVu("Quản lý chức vụ"));
    }                                        
    private void btNhapHangActionPerformed(java.awt.event.ActionEvent evt) {                                         
        addPanel(new PnNhapHang("Quản lý chức vụ"));
    } 
    private void btThongKeActionPerformed(java.awt.event.ActionEvent evt) {                                         
        addPanel(new PnThongKeTheoNgay("Quản lý Thống Kế"));

    }  
    private void btKhoActionPerformed(java.awt.event.ActionEvent evt) {
    	 addPanel(new PnKho("Quản lý Kho"));
    }                                       
    public void addPanel(JPanel pn) {
        pnCenter.removeAll();
        pnCenter.add(pn, BorderLayout.CENTER);
        pnCenter.revalidate();

    }

    
    // Variables declaration - do not modify                     
    private javax.swing.JButton btChucVu;
    private javax.swing.JButton btFood;
    private javax.swing.JButton btHoaDon;
    private javax.swing.JButton btKho;
    private javax.swing.JButton btThongKe;
    private javax.swing.JButton btNhanVien;
    private javax.swing.JButton btViTri;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton btNhapHang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbChucVu;
    private javax.swing.JLabel lbUsername;
    // End of variables declaration                   
}
