/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.User;
import controller.ControllerUser;
import view.inc.PnLeft;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author HungPham
 */
public class FrLogin extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	ControllerUser controller;

    /**
     * Creates new form FrLogin
     */
    public FrLogin() {
        initComponents();
        setLocationRelativeTo(this);
        tfUsername.setBackground(new Color(0, 0, 0, 0));
        pfPassword.setBackground(new Color(0, 0, 0, 0));
        btLogin.setBackground(new Color(0, 0, 0, 0));
        this.setIconImage(new ImageIcon(getClass().getResource("/images/coffee_48.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tfUsername = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        lbText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FAN CHELSEA COFFEE SHOP");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfUsername.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(0, 102, 102));
        tfUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 4, 0));
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        tfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUsernameKeyPressed(evt);
            }
        });
        getContentPane().add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 250, 40));

        pfPassword.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        pfPassword.setForeground(new java.awt.Color(0, 102, 102));
        pfPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 4, 0));
        pfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 250, 40));

        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        btLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btLoginKeyPressed(evt);
            }
        });
        getContentPane().add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 250, 40));

        lbText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbText.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(lbText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        pack();
    }// </editor-fold>                        

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {                                        
        login();
    }                                       

    private void tfUsernameKeyPressed(java.awt.event.KeyEvent evt) {                                      
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pfPassword.requestFocus();
            pfPassword.selectAll();
        }
    }                                     

    private void pfPasswordKeyPressed(java.awt.event.KeyEvent evt) {                                      
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }                                     

    private void btLoginKeyPressed(java.awt.event.KeyEvent evt) {                                   
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }                                  
    private void login() {
        controller = new ControllerUser();
        User item = null;
        String password = new String(pfPassword.getPassword());
        String username = tfUsername.getText();

        try {
            item = new User(0, username, password, "", true);
            if (controller.isUser(item)) {
                
                User login = controller.getUserByUser(username);
                this.setVisible(false);
                FrMain frMain = new FrMain(login);
                frMain.setVisible(true);
            } else {
                lbText.setText("Không thể đăng nhập");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FrLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
         try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
            // set the Quaqua Look and Feel in the UIManager
            
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new FrLogin().setVisible(true);
                }
            });
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FrMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbText;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration                   
}
