/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import library.LibraryDimension;
import library.LibraryName;
import bean.ChucVu;
import controller.ControllerChucVu;

/**
 *
 * @author HungPham
 */
public class PnChucVu extends javax.swing.JPanel implements ActionListener {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	int crow = -1;
    /**
     * Creates new form PnViTri
     */
    ControllerChucVu controller;
    JTable table;
    DefaultTableModel model;

    public PnChucVu(String title) {
        initComponents();
        LibraryName lbName = new LibraryName();
        tfTitleCenter.setForeground(lbName.getColor_Title_PnCenter());
        tfTitleCenter.setFont(lbName.getFont_Title_PnCenter());
        tfTitleCenter.setText(title);
        pnFoodInTacVu.setBackground(lbName.getColor_small_panel());
        pnFoodTacVu.setBackground(lbName.getColor_small_panel());
        pnFoodTimKiem.setBackground(lbName.getColor_small_panel());
        pnFoodInTimKiem.setBackground(lbName.getColor_small_panel());
        JSplitPane sp = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, pnViTriLeft, pnViTriCenter);
        sp.setOneTouchExpandable(true);
        //add(pnViTriTop, BorderLayout.NORTH);
        add(sp, BorderLayout.CENTER);
        pnViTriLeft.setMinimumSize(new Dimension(LibraryDimension.PANEL_LEFT_WIDTH, pnViTriLeft.getSize().height));

        model = new DefaultTableModel() {
            /**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			public boolean isCellEditable(int row, int column) {
                return false;
            }

            public Class<?> getColumnClass(int col) {
                if (col == 0 || col == 2) {
                    return Integer.class;
                } else {
                    return super.getColumnClass(col);
                }
            }
        };

        controller = new ControllerChucVu();

        loadTable(null);

        btChucVuThem.addActionListener(this);
        btChucVuSua.addActionListener(this);
        btChucVuXoa.addActionListener(this);
        btChucVuNhapLai.addActionListener(this);
        btChucVuFind.addActionListener(this);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        pnViTri = new javax.swing.JPanel();
        pnViTriTop = new javax.swing.JPanel();
        tfTitleCenter = new javax.swing.JLabel();
        pnViTriLeft = new javax.swing.JPanel();
        pnFoodTacVu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfChucVuId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfChucVuName = new javax.swing.JTextField();
        pnFoodInTacVu = new javax.swing.JPanel();
        btChucVuThem = new javax.swing.JButton();
        btChucVuSua = new javax.swing.JButton();
        btChucVuNhapLai = new javax.swing.JButton();
        btChucVuXoa = new javax.swing.JButton();
        tfChucVuLuong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnFoodTimKiem = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfChucVuIdFind = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfChucVuNameFind = new javax.swing.JTextField();
        pnFoodInTimKiem = new javax.swing.JPanel();
        btChucVuFind = new javax.swing.JButton();
        pnViTriCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbChucVu = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new java.awt.BorderLayout());

        pnViTri.setLayout(new java.awt.BorderLayout());

        pnViTriTop.setBackground(new java.awt.Color(255, 255, 153));
        pnViTriTop.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tfTitleCenter.setForeground(new java.awt.Color(0, 0, 204));
        tfTitleCenter.setText("Quản lý vị trí");
        pnViTriTop.add(tfTitleCenter);

        pnViTri.add(pnViTriTop, java.awt.BorderLayout.NORTH);

        pnViTriLeft.setBackground(new java.awt.Color(255, 255, 153));
        pnViTriLeft.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Quản lý tác vụ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(51, 51, 255)))); // NOI18N
        pnViTriLeft.setLayout(new java.awt.BorderLayout());

        pnFoodTacVu.setBackground(new java.awt.Color(255, 255, 255));
        pnFoodTacVu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("ID Chức vụ");

        tfChucVuId.setEditable(false);
        tfChucVuId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChucVuIdActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên chức vụ");

        tfChucVuName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChucVuNameActionPerformed(evt);
            }
        });

        pnFoodInTacVu.setBackground(new java.awt.Color(255, 255, 255));

        btChucVuThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_16.png"))); // NOI18N
        btChucVuThem.setText("Thêm");
        btChucVuThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChucVuThemActionPerformed(evt);
            }
        });
        pnFoodInTacVu.add(btChucVuThem);

        btChucVuSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        btChucVuSua.setText("Sửa");
        btChucVuSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChucVuSuaActionPerformed(evt);
            }
        });
        pnFoodInTacVu.add(btChucVuSua);

        btChucVuNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btChucVuNhapLai.setText("Nhập lại");
        pnFoodInTacVu.add(btChucVuNhapLai);

        btChucVuXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.gif"))); // NOI18N
        btChucVuXoa.setText("Xóa");
        pnFoodInTacVu.add(btChucVuXoa);

        jLabel3.setText("Lương cơ bản");

        javax.swing.GroupLayout pnFoodTacVuLayout = new javax.swing.GroupLayout(pnFoodTacVu);
        pnFoodTacVu.setLayout(pnFoodTacVuLayout);
        pnFoodTacVuLayout.setHorizontalGroup(
            pnFoodTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFoodTacVuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnFoodInTacVu, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnFoodTacVuLayout.createSequentialGroup()
                .addGroup(pnFoodTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnFoodTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfChucVuLuong)
                    .addGroup(pnFoodTacVuLayout.createSequentialGroup()
                        .addComponent(tfChucVuId, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfChucVuName)))
        );
        pnFoodTacVuLayout.setVerticalGroup(
            pnFoodTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFoodTacVuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnFoodTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfChucVuId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnFoodTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfChucVuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnFoodTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfChucVuLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(pnFoodInTacVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnViTriLeft.add(pnFoodTacVu, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        pnFoodTimKiem.setBackground(new java.awt.Color(255, 255, 255));
        pnFoodTimKiem.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(0, 0, 204)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)))); // NOI18N

        jLabel5.setText("ID chức vụ");

        tfChucVuIdFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChucVuIdFindActionPerformed(evt);
            }
        });

        jLabel6.setText("Tên chức vụ");

        tfChucVuNameFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChucVuNameFindActionPerformed(evt);
            }
        });

        pnFoodInTimKiem.setBackground(new java.awt.Color(255, 255, 255));

        btChucVuFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon.png"))); // NOI18N
        btChucVuFind.setText("Tìm kiếm");
        pnFoodInTimKiem.add(btChucVuFind);

        javax.swing.GroupLayout pnFoodTimKiemLayout = new javax.swing.GroupLayout(pnFoodTimKiem);
        pnFoodTimKiem.setLayout(pnFoodTimKiemLayout);
        pnFoodTimKiemLayout.setHorizontalGroup(
            pnFoodTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnFoodInTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
            .addGroup(pnFoodTimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFoodTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnFoodTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFoodTimKiemLayout.createSequentialGroup()
                        .addComponent(tfChucVuIdFind, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfChucVuNameFind))
                .addContainerGap())
        );
        pnFoodTimKiemLayout.setVerticalGroup(
            pnFoodTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFoodTimKiemLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(pnFoodTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfChucVuIdFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnFoodTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfChucVuNameFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnFoodInTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(pnFoodTimKiem, java.awt.BorderLayout.CENTER);

        pnViTriLeft.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pnViTri.add(pnViTriLeft, java.awt.BorderLayout.WEST);

        pnViTriCenter.setLayout(new java.awt.BorderLayout());

        tbChucVu.setAutoCreateRowSorter(true);
//        tbChucVu.setBackground(new java.awt.Color(153, 255, 153));
        tbChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            /**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbChucVu.setGridColor(new java.awt.Color(255, 255, 255));
        tbChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbChucVuMousePressed(evt);
            }
        });
        tbChucVu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbChucVuKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbChucVu);
        tbChucVu.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbChucVu.getColumnModel().getColumnCount() > 0) {
            tbChucVu.getColumnModel().getColumn(0).setResizable(false);
            tbChucVu.getColumnModel().getColumn(1).setResizable(false);
            tbChucVu.getColumnModel().getColumn(2).setResizable(false);
            tbChucVu.getColumnModel().getColumn(3).setResizable(false);
        }

        pnViTriCenter.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnViTri.add(pnViTriCenter, java.awt.BorderLayout.CENTER);

        add(pnViTri, java.awt.BorderLayout.CENTER);
    }// </editor-fold>                        

    private void tfChucVuNameActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void tfChucVuIdActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void tfChucVuIdFindActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void tfChucVuNameFindActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void tbChucVuKeyReleased(java.awt.event.KeyEvent evt) {                                     
        setForm();
    }                                    

    private void tbChucVuMousePressed(java.awt.event.MouseEvent evt) {                                      
        setForm();
    }                                     

    private void btChucVuThemActionPerformed(java.awt.event.ActionEvent evt) {                                             

    }                                            

    private void btChucVuSuaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           


    // Variables declaration - do not modify                     
    private javax.swing.JButton btChucVuFind;
    private javax.swing.JButton btChucVuNhapLai;
    private javax.swing.JButton btChucVuSua;
    private javax.swing.JButton btChucVuThem;
    private javax.swing.JButton btChucVuXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnFoodInTacVu;
    private javax.swing.JPanel pnFoodInTimKiem;
    private javax.swing.JPanel pnFoodTacVu;
    private javax.swing.JPanel pnFoodTimKiem;
    private javax.swing.JPanel pnViTri;
    private javax.swing.JPanel pnViTriCenter;
    private javax.swing.JPanel pnViTriLeft;
    private javax.swing.JPanel pnViTriTop;
    private javax.swing.JTable tbChucVu;
    private javax.swing.JTextField tfChucVuId;
    private javax.swing.JTextField tfChucVuIdFind;
    private javax.swing.JTextField tfChucVuLuong;
    private javax.swing.JTextField tfChucVuName;
    private javax.swing.JTextField tfChucVuNameFind;
    private javax.swing.JLabel tfTitleCenter;
    // End of variables declaration                   

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btChucVuThem) {
            ChucVu item = new ChucVu(0, tfChucVuName.getText(), Integer.parseInt(tfChucVuLuong.getText()));
            if (controller.add(item) > 0) {
                loadTable(null);
                JOptionPane.showMessageDialog(null, "Thêm thành công");
            }
        } else if (e.getSource() == btChucVuSua) {
            ChucVu item = new ChucVu(Integer.parseInt(tfChucVuId.getText()), tfChucVuName.getText(), Integer.parseInt(tfChucVuLuong.getText()));
            crow = tbChucVu.getSelectedRow();
            if (controller.edit(item) > 0) {
                loadTable(null);
                JOptionPane.showMessageDialog(null, "Sửa thành công");
                tbChucVu.setRowSelectionInterval(crow, crow);
            }
        } else if (e.getSource() == btChucVuNhapLai){
            resetForm();
        } else if (e.getSource() == btChucVuXoa){
             int id = 0;
            try{
                id = Integer.parseInt(tfChucVuId.getText());
            }
            catch (NumberFormatException ex){
                System.out.println("Phải nhập số vào ID");
            }
            ChucVu item = new ChucVu(id, tfChucVuNameFind.getText(), 0);
            if (controller.del(item) > 0) {
                loadTable(null);
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                resetForm();
            }
        } else if (e.getSource() == btChucVuFind){
            int id = 0;
            try{
                id = Integer.parseInt(tfChucVuIdFind.getText());
            }
            catch (NumberFormatException ex){
                System.out.println("Phải nhập số vào ID");
            }
            
            ChucVu cvFind = new ChucVu(id, tfChucVuNameFind.getText(), 0);
            loadTable(cvFind);
            
        } 
    }

    public void loadTable(ChucVu item) {
        controller.loadTable(tbChucVu, model, item);
        controller.setWidthHeightTable(tbChucVu);
    }

    public void setForm() {
        crow = tbChucVu.getSelectedRow();
        tfChucVuId.setText(tbChucVu.getValueAt(crow, 0).toString());
        tfChucVuName.setText(tbChucVu.getValueAt(crow, 1).toString());
        tfChucVuLuong.setText(tbChucVu.getValueAt(crow, 2).toString());
    }
    private void resetForm() {
        tfChucVuId.setText("");
        tfChucVuName.setText("");
        tfChucVuLuong.setText("");
        crow = -1;
    }
}
